# Generated by Django 5.0 on 2023-12-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_blog_full_content_alter_blog_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='full_content',
            field=models.TextField(),
        ),
    ]
