# Generated by Django 5.0 on 2023-12-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_alter_blog_content_alter_blog_full_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='full_content',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
    ]
